mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'puppetlabs-apt'
mod 'puppetlabs-powershell'
mod 'puppetlabs-reboot'
mod 'puppetlabs-pwshlib'
