mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
